
#
# Deployment Configuration
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigfox-callback-prod
  labels:
    app: sigfox-callback-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sigfox-callback-prod
  template:
    metadata:
      labels:
        app: sigfox-callback-prod
        version: 1.0.RELEASE
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kubernetes.io/hostname
#                    operator: In
#                    values:
#                      - k8sworker1
#                      - k8sworker2
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-registry-credentials
      containers:
      - name: sigfox-callback-prod
        image: registry.parlacom.net:5000/leadingquest/leadingquest-kinder:prod-v1.0
        imagePullPolicy: Always
        volumeMounts:
          - name: sigfox-callback-prod-data
            mountPath: "/var"
        resources:
          requests:
            memory: "900Mi"
            cpu: "0.5"
          limits:
            memory: "900Mi"
        ports:
          - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SERVER_PORT
          value: "8080"
        - name: SIGFOX_LOG_ENABLED
          value: "false"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 50
          periodSeconds: 20
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 50
          periodSeconds: 20
      volumes:
        - name: sigfox-callback-prod-data
          persistentVolumeClaim:
            claimName: pvc-nfs-api-claim
---

#
# Service Configuration
#
apiVersion: v1
kind: Service
metadata:
  name: sigfox-callback-prod
  labels:
    app: sigfox-callback-prod
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: sigfox-callback-prod

---

#
# Horizontal Pod Autoscaler
#
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sigfox-callback-prod
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sigfox-callback-prod
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 900Mi

---

#
# Service Monitor
#
# https://github.com/prometheus-operator/prometheus-operator
# https://tanzu.vmware.com/developer/guides/spring/spring-prometheus/
# https://dimitr.im/collecting-application-metrics-with-istio
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prometheus-sigfox-callback-prod-service-monitor
  labels:
    app: sigfox-callback-prod
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sigfox-callback-prod
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"

---

#
# Application PROD Configuration
#
# kubectl create -f k8s-deploy.yml
#
# kubectl delete configmap sigfox-callback-prod
#
# kubectl edit configmap sigfox-callback-prod
#
# kubectl describe configmaps sigfox-callback-prod
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: sigfox-callback-prod
data:
  application-prod.properties: |-

    # ---------------------------------------------------------------------------------------------
    # PROD Profile

    # TimeZone Config............
    time-zone=UTC

    # Main Settings ...........
    spring.application.name=sigfox-callback-prod
    server.shutdown=graceful

    # Metrics ...................
    management.endpoint.metrics.enabled=true
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=*
    management.metrics.export.prometheus.enabled=true

    # Wavefront .................
    wavefront.application.name=sigfox-callback-prod
    wavefront.application.service=data-events
    wavefront.freemium-account=false
    management.metrics.export.wavefront.api-token=9b8d88f6-7ba5-4f1f-95b0-b920ff95c07e
    management.metrics.export.wavefront.uri=https://wavefront.surf
    #management.metrics.export.wavefront.source=sigfox-callback-prod

    # Sigfox App Config  .........
    sigfox.log.enabled=false
    sigfox.log.directory=/var/log/sigfox/callback/archive

    # Datasource
    sigfox.datasource.device.r2dbc=r2dbc:mariadb://mvno8:klu6%40jix8@74.208.65.53:3306/mya2billing8?tinyInt1isBit=false&sessionVariables=time_zone='+00:00',wait_timeout=1000000
    sigfox.datasource.account.r2dbc=r2dbc:mariadb://mvno8:klu6%40jix8@db8acct.parlacom.net:3306/radius8?tinyInt1isBit=false&sessionVariables=time_zone='+00:00',wait_timeout=1000000
